from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.core.models import utc_now


class CodegenRuntime:
    def __init__(self, root: Path) -> None:
        self.root = root

    def generate(
        self,
        session_dir: Path,
        blocker: dict[str, Any],
        connection_plan: dict[str, Any],
        build_plan: dict[str, Any],
    ) -> dict[str, Any]:
        runtime_dir = session_dir / "codegen"
        runtime_dir.mkdir(parents=True, exist_ok=True)

        adapter = (connection_plan.get("recommended_adapter") or {}).get("adapter_id", "unknown")
        script_path = runtime_dir / f"generated_{adapter.replace('-', '_')}_adapter.py"
        script_path.write_text(
            self._adapter_stub(adapter, blocker, build_plan)
        )

        queue = {
            "generated_at": utc_now(),
            "objective": "Generate the next session-specific adapter/probe/build helper needed to continue autonomously.",
            "adapter": adapter,
            "files_generated": [str(script_path)],
            "machine_solvable": blocker.get("machine_solvable", False),
            "next_execution_step": f"Run or refine {script_path.name} inside the session.",
        }
        queue_path = runtime_dir / "execution-queue.json"
        queue_path.write_text(json.dumps(queue, indent=2))
        return {
            "generated_files": [str(script_path), str(queue_path)],
            "summary": f"Generated runtime artifacts for adapter path `{adapter}`.",
            "queue_path": str(queue_path),
        }

    def _adapter_stub(self, adapter: str, blocker: dict[str, Any], build_plan: dict[str, Any]) -> str:
        return f"""from __future__ import annotations

\"\"\"Autogenerated session-specific adapter stub.

Adapter path: {adapter}
Blocker type: {blocker.get('blocker_type')}
Recommended OS path: {build_plan.get('os_path')}

This file is intentionally session-local. Refine it before promoting anything
reusable back into master/.
\"\"\"


def run() -> dict[str, object]:
    return {{
        "adapter": "{adapter}",
        "status": "stub",
        "next_step": "Refine this generated adapter with real device-specific logic.",
    }}
"""
